package worktree

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Hy0sh/worktree-manager/internal/config"
	"github.com/Hy0sh/worktree-manager/internal/dbengine"
)

// snapshotOverride is the compose file wtm generates in the worktree. Handing
// the restore to the project's own compose would make the behaviour depend on
// the branch the worktree was cut from, since that file is versioned. wtm
// carries it instead, so any project gets the restore without changing a line.
const snapshotOverride = ".wtm-snapshot.yaml"

// portsOverride is generated whenever a project publishes literal ports.
const portsOverride = ".wtm-ports.yaml"

// ensureSnapshotAssets writes the restore script and the generated compose
// file. Idempotent, and run on every start so a worktree created before they
// existed picks them up too. The script body comes from the project's engine;
// all of them rely on docker-entrypoint-initdb.d only running on an empty
// data directory, so a fresh worktree restores and an existing one is left
// alone, with no race against the application's own migrate.
func ensureSnapshotAssets(o Options, dest string) error {
	if !o.Project.Dump {
		return nil
	}
	eng, err := dbengine.ByName(o.Project.BackupConfig().DBEngine)
	if err != nil {
		return err
	}
	if err := writeRestoreScript(o.BackupsDir, o.Name, eng); err != nil {
		return fmt.Errorf("writing the restore script: %w", err)
	}
	if err := writeSnapshotOverride(dest, o.Project.BackupConfig().DBService); err != nil {
		return fmt.Errorf("writing the snapshot compose file: %w", err)
	}
	return nil
}

// writeRestoreScript puts the script next to the dump, where the worktree's
// .db-snapshot symlink makes it reachable from the container.
func writeRestoreScript(backupsDir, project string, eng dbengine.Engine) error {
	// The name is interpolated into a shell script that runs inside the
	// database container, so it is checked here too and not only at
	// registration: config.json can be hand-edited.
	if err := config.ValidateIdentifier("project name", project); err != nil {
		return err
	}
	dir := filepath.Join(backupsDir, project)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "restore-snapshot.sh"), []byte(eng.RestoreScript(project)), 0o755)
}

// writeSnapshotOverride generates the compose file mounting the dump and the
// restore script into the database service.
func writeSnapshotOverride(dest, dbService string) error {
	// Interpolated into a generated YAML document, where a newline would inject
	// arbitrary compose keys, volume mounts included.
	if err := config.ValidateIdentifier("database service", dbService); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by wtm, do not edit. Mounts the central dump so a fresh
# database restores instead of replaying the whole migration history.
services:
  %s:
    volumes:
      - ./.db-snapshot:/db-snapshot:ro
      - ./.db-snapshot/restore-snapshot.sh:/docker-entrypoint-initdb.d/10-wtm-restore.sh:ro
`, dbService)
	return os.WriteFile(filepath.Join(dest, snapshotOverride), []byte(body), 0o644)
}
