package worktree

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Hy0sh/worktree-manager/internal/compose"
	"github.com/Hy0sh/worktree-manager/internal/config"
)

// snapshotOverride is the compose file wtm generates in the worktree. Handing
// the restore to the project's own compose would make the behaviour depend on
// the branch the worktree was cut from, since that file is versioned. wtm
// carries it instead, so any project gets the restore without changing a line.
const snapshotOverride = ".wtm-snapshot.yaml"

// portsOverride is generated whenever a project publishes literal ports.
const portsOverride = ".wtm-ports.yaml"

// restoreScript runs inside the database container. Postgres only executes
// docker-entrypoint-initdb.d on an empty data directory, which is exactly the
// wanted semantics: a fresh worktree restores, an existing one is left alone.
// It also rules out any race with the application's own migrate, because the
// database only reports healthy once this has finished.
const restoreScript = `#!/bin/sh
# Generated by wtm. Restores the pre-migrated dump into a brand new database.
set -e
dump="/db-snapshot/%s.dump"
if [ ! -f "$dump" ]; then
  echo "wtm: no dump at $dump, starting from an empty database"
  exit 0
fi
echo "wtm: restoring $dump into ${POSTGRES_DB:-postgres}"
pg_restore --no-owner --no-privileges --exit-on-error --single-transaction \
  -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-postgres}" "$dump"
echo "wtm: restore done, migrations already applied"
`

// ensureSnapshotAssets writes the restore script and the generated compose
// file. Idempotent, and run on every start so a worktree created before they
// existed picks them up too.
func ensureSnapshotAssets(o Options, dest string) error {
	if !o.Project.Dump {
		return nil
	}
	if err := writeRestoreScript(o.BackupsDir, o.Name); err != nil {
		return fmt.Errorf("writing the restore script: %w", err)
	}
	if err := writeSnapshotOverride(dest, o.Project.BackupConfig().DBService); err != nil {
		return fmt.Errorf("writing the snapshot compose file: %w", err)
	}
	return nil
}

// writeRestoreScript puts the script next to the dump, where the worktree's
// .db-snapshot symlink makes it reachable from the container.
func writeRestoreScript(backupsDir, project string) error {
	// The name is interpolated into a shell script that runs inside the
	// database container, so it is checked here too and not only at
	// registration: config.json can be hand-edited.
	if err := config.ValidateIdentifier("project name", project); err != nil {
		return err
	}
	dir := filepath.Join(backupsDir, project)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	body := fmt.Sprintf(restoreScript, project)
	return os.WriteFile(filepath.Join(dir, "restore-snapshot.sh"), []byte(body), 0o755)
}

// writeSnapshotOverride generates the compose file mounting the dump and the
// restore script into the database service.
func writeSnapshotOverride(dest, dbService string) error {
	// Interpolated into a generated YAML document, where a newline would inject
	// arbitrary compose keys, volume mounts included.
	if err := config.ValidateIdentifier("database service", dbService); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by wtm, do not edit. Mounts the central dump so a fresh
# database restores instead of replaying the whole migration history.
services:
  %s:
    volumes:
      - ./.db-snapshot:/db-snapshot:ro
      - ./.db-snapshot/restore-snapshot.sh:/docker-entrypoint-initdb.d/10-wtm-restore.sh:ro
`, dbService)
	return os.WriteFile(filepath.Join(dest, snapshotOverride), []byte(body), 0o644)
}

// composeFileEnv builds the COMPOSE_FILE value that adds the generated file to
// the ones docker compose would have picked on its own. wtc spreads its own
// environment into the compose commands it runs, so this reaches docker
// without wtc needing to know about it.
//
// The names come from the project, not from the worktree: wtc copies the
// compose file in as part of `start`, so on a first start it does not exist
// yet when this runs, only by the time docker is invoked.
func composeFileEnv(projectDir, dest string) (string, error) {
	files, err := compose.Files(projectDir)
	if err != nil {
		return "", err
	}
	inWorktree := make([]string, 0, len(files)+1)
	for _, f := range files {
		inWorktree = append(inWorktree, filepath.Join(dest, filepath.Base(f)))
	}
	inWorktree = append(inWorktree, filepath.Join(dest, snapshotOverride))
	return "COMPOSE_FILE=" + joinComposeFiles(inWorktree), nil
}

// joinComposeFiles uses the separator docker compose expects on this platform.
func joinComposeFiles(files []string) string {
	out := ""
	for i, f := range files {
		if i > 0 {
			out += string(os.PathListSeparator)
		}
		out += f
	}
	return out
}
