package worktree

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Hy0sh/worktree-manager/internal/backup"
	"github.com/Hy0sh/worktree-manager/internal/config"
	"github.com/Hy0sh/worktree-manager/internal/dbengine"
	"github.com/Hy0sh/worktree-manager/internal/safefile"
)

// snapshotOverride is generated rather than left to the project's own compose,
// which is versioned: the restore would then depend on the branch the worktree
// was cut from. Carrying it here means any project gets it untouched.
const snapshotOverride = ".wtm-snapshot.yaml"

// portsOverride is generated whenever a project publishes literal ports.
const portsOverride = ".wtm-ports.yaml"

// ensureSnapshotAssets is idempotent and runs on every start, so a worktree
// created before these files existed picks them up too. Every engine's script
// relies on docker-entrypoint-initdb.d only running on an empty data directory:
// a fresh worktree restores, an existing one is left alone, and nothing races
// the application's own migrate.
func ensureSnapshotAssets(o Options, dest string) error {
	if !o.Project.Dump {
		return nil
	}
	cfg := o.Project.BackupConfig()
	if dbengine.IsFileBased(cfg.DBEngine) {
		return ensureDBFileCopy(o, dest, cfg)
	}
	eng, err := dbengine.ByName(cfg.DBEngine)
	if err != nil {
		return err
	}
	if err := writeRestoreScript(o.BackupsDir, o.Name, eng); err != nil {
		return fmt.Errorf("writing the restore script: %w", err)
	}
	if err := writeSnapshotOverride(dest, cfg.DBService); err != nil {
		return fmt.Errorf("writing the snapshot compose file: %w", err)
	}
	return nil
}

// ensureDBFileCopy is the whole restore story of a file-based engine: the
// pre-migrated file goes where the application expects it, and only when
// nothing is there yet, so a database being worked in is never clobbered.
func ensureDBFileCopy(o Options, dest string, cfg config.Backup) error {
	// Checked here and not only at registration: config.json can be
	// hand-edited, and this path reaches filepath.Join against the worktree.
	if err := config.ValidateRelativePath("db_path", cfg.DBPath); err != nil {
		return err
	}
	src := filepath.Join(o.BackupsDir, o.Name, o.Name+".dump")
	if _, err := os.Stat(src); err != nil {
		o.logf("no dump yet: the database starts empty, run `wtm backup refresh %s` to build one", o.Name)
		return nil
	}
	return copyFile(src, dest, filepath.Join(dest, cfg.DBPath), keepWorktreeCopies)
}

// writeRestoreScript puts the script next to the dump, where the worktree's
// .db-snapshot symlink makes it reachable from the container.
func writeRestoreScript(backupsDir, project string, eng dbengine.Engine) error {
	// The name is interpolated into a shell script that runs inside the
	// database container, so it is checked here too and not only at
	// registration: config.json can be hand-edited.
	if err := config.ValidateIdentifier("project name", project); err != nil {
		return err
	}
	dir := filepath.Join(backupsDir, project)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, backup.RestoreScriptName), []byte(eng.RestoreScript(project)), 0o755)
}

func writeSnapshotOverride(dest, dbService string) error {
	// Interpolated into a generated YAML document, where a newline would inject
	// arbitrary compose keys, volume mounts included.
	if err := config.ValidateIdentifier("database service", dbService); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by wtm, do not edit. Mounts the central dump so a fresh
# database restores instead of replaying the whole migration history.
services:
  %s:
    volumes:
      - ./.db-snapshot:/db-snapshot:ro
      - ./.db-snapshot/%s:/docker-entrypoint-initdb.d/10-wtm-restore.sh:ro
`, dbService, backup.RestoreScriptName)
	return safefile.Write(dest, filepath.Join(dest, snapshotOverride), []byte(body), 0o644)
}
