// Package dbengine describes how each supported engine is probed, dumped and
// restored. Every argv runs inside the database container through `docker
// compose exec -T`, wrapped in `sh -c` where a credential must expand there.
package dbengine

import (
	"fmt"
	"path"
	"slices"
	"strings"
)

type Engine interface {
	Name() string
	// DetectImage reports whether this engine runs the given image repo
	// (already lowercased and stripped of tag and digest).
	DetectImage(repo string) bool
	// ReadyArgs succeeds once the server accepts connections.
	ReadyArgs(user string) []string
	DropTempDBArgs(user, db string) []string
	// CreateTempDBArgs is nil for engines creating databases implicitly.
	CreateTempDBArgs(user, db string) []string
	// DumpArgs writes the dump of db to stdout.
	DumpArgs(user, db string) []string
	// ObjectCountArgs writes to stdout how many tables, or collections, db
	// holds. A migration that never targeted the throwaway database leaves it
	// at zero, which is the only way to tell that dump from a real one.
	ObjectCountArgs(user, db string) []string
	// RestoreScript is the docker-entrypoint-initdb.d body restoring the dump.
	RestoreScript(project string) string
}

var engines = []Engine{postgres{}, newMySQL(), newMariaDB(), mongodb{}}

// ByName resolves an engine; the empty name is postgres, which is what every
// project registered before db_engine existed means.
func ByName(name string) (Engine, error) {
	if name == "" {
		name = "postgres"
	}
	for _, e := range engines {
		if e.Name() == name {
			return e, nil
		}
	}
	return nil, fmt.Errorf("unknown database engine %q (supported: %s)", name, strings.Join(Names(), ", "))
}

// Detect finds the engine running a compose image, e.g. "postgres:16-alpine".
func Detect(image string) (Engine, bool) {
	repo := imageRepo(image)
	if repo == "" {
		return nil, false
	}
	for _, e := range engines {
		if e.DetectImage(repo) {
			return e, true
		}
	}
	return nil, false
}

// fileBased are engines without a server: no compose service to probe, the
// snapshot is the database file itself. They never resolve through ByName;
// callers branch on IsFileBased first.
var fileBased = []string{"sqlite"}

func IsFileBased(name string) bool { return slices.Contains(fileBased, name) }

// Valid reports whether name designates a supported engine, file-based ones
// included. The empty name is the postgres default.
func Valid(name string) bool {
	if IsFileBased(name) {
		return true
	}
	_, err := ByName(name)
	return err == nil
}

func Names() []string {
	names := make([]string, 0, len(engines)+len(fileBased))
	for _, e := range engines {
		names = append(names, e.Name())
	}
	return append(names, fileBased...)
}

// imageRepo strips tag and digest: "bitnami/postgresql:16" -> "bitnami/postgresql".
func imageRepo(image string) string {
	image = strings.ToLower(strings.TrimSpace(image))
	if i := strings.LastIndex(image, "@"); i >= 0 {
		image = image[:i]
	}
	if i := strings.LastIndex(image, ":"); i > strings.LastIndex(image, "/") {
		image = image[:i]
	}
	return image
}

// baseIs matches the last path segment exactly: an image that merely mentions
// an engine (a proxy, a sidecar) must not be taken for the server itself, since
// missing a match costs a question while matching wrong breaks the backup.
func baseIs(repo string, names ...string) bool {
	return slices.Contains(names, path.Base(repo))
}

// restoreScript wraps the engine's own restore lines in the frame the three
// share: a missing dump means a worktree starting on an empty database, not a
// failed initialisation.
func restoreScript(project, restore string) string {
	return `#!/bin/sh
# Generated by wtm. Restores the pre-migrated dump into a brand new database.
set -e
dump="/db-snapshot/` + project + `.dump"
# The entrypoint runs this as the database's own user, not as root: a mount it
# cannot read has to fail here, or the worktree comes up silently empty.
if [ -d /db-snapshot ] && { [ ! -r /db-snapshot ] || [ ! -x /db-snapshot ]; }; then
  echo "wtm: /db-snapshot is not readable by $(id -un): fix its permissions, or the dump cannot be restored" >&2
  exit 1
fi
if [ ! -f "$dump" ]; then
  echo "wtm: no dump at $dump, starting from an empty database"
  exit 0
fi
if [ ! -r "$dump" ]; then
  echo "wtm: $dump is not readable by $(id -un)" >&2
  exit 1
fi
` + restore + `
echo "wtm: restore done, migrations already applied"
`
}

// TempDBName keeps the throwaway database identifier valid unquoted in every
// engine: my-app would not be.
func TempDBName(project string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(project) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String() + "_snapshot_tmp"
}
