package dbengine

type mongodb struct{}

func (mongodb) Name() string { return "mongodb" }

func (mongodb) DetectImage(repo string) bool {
	return baseIs(repo, "mongo", "mongodb", "mongodb-community-server",
		"mongodb-enterprise-server", "mongodb-atlas-local", "percona-server-mongodb")
}

// sh runs cmd with the root auth flags appended, but only when the container
// declares a root user: a no-auth mongo accepts none of them.
// SECURITY: cmd is concatenated into a shell line. Only literals and
// identifiers sanitised by TempDBName may reach it; anything coming from
// config or user input would be a shell injection inside the container.
func (mongodb) sh(cmd string) []string {
	return []string{"sh", "-c",
		`if [ -n "$MONGO_INITDB_ROOT_USERNAME" ]; then set -- -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin; else set --; fi; exec ` + cmd + ` "$@"`}
}

func (m mongodb) ReadyArgs(string) []string {
	return m.sh(`mongosh --quiet --eval 'db.runCommand({ping:1})'`)
}

func (m mongodb) DropTempDBArgs(_, db string) []string {
	return m.sh(`mongosh --quiet --eval 'db.getSiblingDB("` + db + `").dropDatabase()'`)
}

// CreateTempDBArgs is nil: mongo creates a database on its first write.
func (mongodb) CreateTempDBArgs(_, _ string) []string { return nil }

func (m mongodb) DumpArgs(_, db string) []string {
	return m.sh(`mongodump --archive --db=` + db)
}

// RestoreScript runs against the init phase's temporary mongod, which the
// entrypoint starts without authentication on localhost.
func (mongodb) RestoreScript(project string) string {
	return `#!/bin/sh
# Generated by wtm. Restores the pre-migrated dump into a brand new database.
set -e
dump="/db-snapshot/` + project + `.dump"
if [ ! -f "$dump" ]; then
  echo "wtm: no dump at $dump, starting from an empty database"
  exit 0
fi
echo "wtm: restoring $dump into ${MONGO_INITDB_DATABASE:-test}"
mongorestore --archive="$dump" --nsFrom='` + TempDBName(project) + `.*' --nsTo="${MONGO_INITDB_DATABASE:-test}.*"
echo "wtm: restore done, migrations already applied"
`
}
