package dbengine

import "strings"

// mysqlFamily covers mysql and mariadb, which differ only by binary names,
// the root-password variable and the database variable. Credentials go
// through MYSQL_PWD (both servers honour it) so an empty password
// (MYSQL_ALLOW_EMPTY_PASSWORD) works and nothing is prompted.
type mysqlFamily struct {
	name     string
	images   []string // image basenames that are this server
	client   string   // mysql | mariadb
	dump     string   // mysqldump | mariadb-dump
	password string   // shell expression for the root password
	database string   // shell expression for the application database name
}

func newMySQL() mysqlFamily {
	return mysqlFamily{
		name: "mysql", images: []string{"mysql", "mysql-server", "mysql-cluster", "percona", "percona-server"},
		client: "mysql", dump: "mysqldump",
		password: `"$MYSQL_ROOT_PASSWORD"`,
		database: `"${MYSQL_DATABASE:-mysql}"`,
	}
}

func newMariaDB() mysqlFamily {
	return mysqlFamily{
		name: "mariadb", images: []string{"mariadb", "mariadb-galera"},
		client: "mariadb", dump: "mariadb-dump",
		password: `"${MARIADB_ROOT_PASSWORD:-$MYSQL_ROOT_PASSWORD}"`,
		database: `"${MARIADB_DATABASE:-${MYSQL_DATABASE:-mysql}}"`,
	}
}

func (e mysqlFamily) Name() string                 { return e.name }
func (e mysqlFamily) DetectImage(repo string) bool { return baseIs(repo, e.images...) }

// sh wraps a command so the root password expands inside the container.
// SECURITY: cmd is concatenated into a shell line. Only literals and
// identifiers sanitised by TempDBName may reach it; anything coming from
// config or user input would be a shell injection inside the container.
func (e mysqlFamily) sh(cmd string) []string {
	return []string{"sh", "-c", "MYSQL_PWD=" + e.password + " exec " + cmd}
}

// ReadyArgs runs an authenticated query rather than a ping: during the
// image's first initialisation a temporary server already answers pings on
// the socket while root's password is not set up yet, and commands sent then
// are refused. The query only succeeds on the final, fully configured server.
func (e mysqlFamily) ReadyArgs(string) []string {
	return e.sh(e.client + ` -uroot -e "SELECT 1"`)
}

func (e mysqlFamily) DropTempDBArgs(_, db string) []string {
	return e.sh(e.client + ` -uroot -e "DROP DATABASE IF EXISTS ` + db + `;"`)
}

func (e mysqlFamily) CreateTempDBArgs(_, db string) []string {
	return e.sh(e.client + ` -uroot -e "CREATE DATABASE ` + db + `;"`)
}

func (e mysqlFamily) DumpArgs(_, db string) []string {
	return e.sh(e.dump + " --single-transaction --routines --triggers " + db)
}

// ObjectCountArgs asks for the count without headers or framing, so stdout is
// the bare number the caller parses.
func (e mysqlFamily) ObjectCountArgs(_, db string) []string {
	return e.sh(e.client + ` -uroot -N -B -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '` + db + `';"`)
}

// RestoreScript runs during the image's init phase: the entrypoint has
// already created root with its password, and the temporary server listens
// on the local socket only.
func (e mysqlFamily) RestoreScript(project string) string {
	return `#!/bin/sh
# Generated by wtm. Restores the pre-migrated dump into a brand new database.
set -e
dump="/db-snapshot/` + project + `.dump"
if [ ! -f "$dump" ]; then
  echo "wtm: no dump at $dump, starting from an empty database"
  exit 0
fi
echo "wtm: restoring $dump into ` + strings.ReplaceAll(e.database, `"`, ``) + `"
MYSQL_PWD=` + e.password + ` ` + e.client + ` -uroot ` + e.database + ` < "$dump"
echo "wtm: restore done, migrations already applied"
`
}
