package dbengine

type postgres struct{}

func (postgres) Name() string { return "postgres" }

func (postgres) DetectImage(repo string) bool {
	return baseIs(repo, "postgres", "postgresql", "postgis", "postgresql-repmgr")
}

func (postgres) ReadyArgs(user string) []string {
	return []string{"pg_isready", "-U", user}
}

func (postgres) DropTempDBArgs(user, db string) []string {
	return []string{"psql", "-U", user, "-c", "DROP DATABASE IF EXISTS " + db + ";"}
}

func (postgres) CreateTempDBArgs(user, db string) []string {
	return []string{"psql", "-U", user, "-c", "CREATE DATABASE " + db + ";"}
}

func (postgres) DumpArgs(user, db string) []string {
	return []string{"pg_dump", "-U", user, "-Fc", "--no-owner", "--no-privileges", "-d", db}
}

// ObjectCountArgs counts across every schema, not just public: a project can
// migrate into named schemas and still be perfectly populated.
func (postgres) ObjectCountArgs(user, db string) []string {
	return []string{"psql", "-U", user, "-d", db, "-t", "-A", "-c",
		"select count(*) from information_schema.tables where table_schema not in ('pg_catalog','information_schema')"}
}

// RestoreScript relies on docker-entrypoint-initdb.d only running on an empty
// data directory: a fresh worktree restores, an existing one is left alone. It
// also rules out any race with the application's own migrate, because the
// database only reports healthy once this has finished.
func (postgres) RestoreScript(project string) string {
	return `#!/bin/sh
# Generated by wtm. Restores the pre-migrated dump into a brand new database.
set -e
dump="/db-snapshot/` + project + `.dump"
if [ ! -f "$dump" ]; then
  echo "wtm: no dump at $dump, starting from an empty database"
  exit 0
fi
echo "wtm: restoring $dump into ${POSTGRES_DB:-postgres}"
pg_restore --no-owner --no-privileges --exit-on-error --single-transaction \
  -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-postgres}" "$dump"
echo "wtm: restore done, migrations already applied"
`
}
