package stack

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/Hy0sh/worktree-manager/internal/compose"
)

// baseOffset, the formula and the fallback are taken verbatim from
// worktree-compose. Keeping them identical is not a detail: worktrees created
// before this tool stopped shelling out to it must keep the exact same ports.
const baseOffset = 20000

// DefaultStride applies when the project does not configure one.
const DefaultStride = 1

// Allocation is one published port, rebased for a given worktree.
type Allocation struct {
	Service   string
	Var       string
	Port      int
	Container string
}

// AllocatePort rebases a default port for a worktree index.
func AllocatePort(defaultPort, index, stride, projectOffset int) (int, error) {
	if index < 1 {
		return 0, fmt.Errorf("worktree index %d was never allocated (wtm bug: the index resolver must run before ports are computed)", index)
	}
	port := baseOffset + projectOffset + defaultPort + index*stride
	if port > 65535 {
		port = defaultPort + 100*index
	}
	if port > 65535 || port < 1024 {
		return 0, fmt.Errorf("cannot allocate a port for default %d at worktree index %d: %d is out of range (1024-65535)",
			defaultPort, index, port)
	}
	return port, nil
}

// Allocate rebases every published port of the compose file, whether it is
// written as a variable or as a literal. A literal cannot be overridden
// through the environment, so it is rebased through a generated compose file
// instead; see PortsOverride.
func Allocate(services []compose.ServicePort, index, stride, projectOffset int) ([]Allocation, error) {
	var out []Allocation
	seen := map[int]string{}
	for _, s := range services {
		defaultPort, err := strconv.Atoi(s.Host)
		if err != nil {
			continue
		}
		port, err := AllocatePort(defaultPort, index, stride, projectOffset)
		if err != nil {
			return nil, err
		}
		label := s.Var
		if label == "" {
			label = s.Service + ":" + s.Container
		}
		if other, clash := seen[port]; clash {
			return nil, fmt.Errorf("port collision in worktree %d: %d is assigned to both %s and %s",
				index, port, other, label)
		}
		seen[port] = label
		out = append(out, Allocation{Service: s.Service, Var: s.Var, Port: port, Container: s.Container})
	}
	return out, nil
}

// Stride reads the project's port stride, from .wtcrc.json when present so an
// existing setup keeps working untouched.
func Stride(projectDir string) int {
	var cfg struct {
		PortStride int `json:"portStride"`
	}
	data, err := os.ReadFile(filepath.Join(projectDir, ".wtcrc.json"))
	if err == nil && json.Unmarshal(data, &cfg) == nil && cfg.PortStride > 0 {
		return cfg.PortStride
	}
	var pkg struct {
		Wtc struct {
			PortStride int `json:"portStride"`
		} `json:"wtc"`
	}
	data, err = os.ReadFile(filepath.Join(projectDir, "package.json"))
	if err == nil && json.Unmarshal(data, &pkg) == nil && pkg.Wtc.PortStride > 0 {
		return pkg.Wtc.PortStride
	}
	return DefaultStride
}

// PortsOverride renders the compose file rebasing the ports a project wrote as
// literals, which no environment variable can reach. Compose appends `ports`
// when merging, so the list has to be replaced with !override, and replacing
// it means restating every port of that service.
//
// This is what lets a project be used untouched: without it, a worktree stack
// would publish the very ports its main stack already holds.
func PortsOverride(allocations []Allocation) string {
	byService := map[string][]Allocation{}
	var order []string
	literal := map[string]bool{}
	for _, a := range allocations {
		if _, seen := byService[a.Service]; !seen {
			order = append(order, a.Service)
		}
		byService[a.Service] = append(byService[a.Service], a)
		if a.Var == "" {
			literal[a.Service] = true
		}
	}
	var b strings.Builder
	for _, service := range order {
		if !literal[service] {
			continue // reachable through the .env, nothing to override
		}
		if b.Len() == 0 {
			b.WriteString("# Generated by wtm, do not edit. Rebases the ports this project\n" +
				"# publishes as literals, so the worktree stack does not fight the main one.\n" +
				"services:\n")
		}
		// Service names come from the project's own compose file, which docker
		// already constrains, but this document is generated so the check is
		// cheap insurance against a newline smuggling in extra keys.
		if strings.ContainsAny(service, "\n\r\"'#{}[]") {
			continue
		}
		fmt.Fprintf(&b, "  %s:\n    ports: !override\n", service)
		for _, a := range byService[service] {
			fmt.Fprintf(&b, "      - \"%d:%s\"\n", a.Port, a.Container)
		}
	}
	return b.String()
}
